name: Release

on:
  workflow_dispatch:
    inputs:
      VersionPrefix:
        type: string
        description: The version of the application
        required: true
        default: 1.2.0
      VersionSuffix:
        type: string
        description: The version suffix of the application (for example rc.1)

run-name: ${{ inputs.VersionSuffix && format('{0}-{1}', inputs.VersionPrefix, inputs.VersionSuffix) || inputs.VersionPrefix }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      
      - name: Build AppRegistrationSecretWatcher Azure Functions
        run: dotnet publish 
          --property:Configuration=Release
          --property:VersionPrefix=${{ github.event.inputs.VersionPrefix }}
          --property:VersionSuffix=${{ github.event.inputs.VersionSuffix }}
          --output ./publish
          "src/Functions/Functions.csproj"

      - name: Package the AppRegistrationSecretWatcher Azure Functions
        run: cd ./publish && zip -r ../PosInformatique.Azure.Identity.AppRegistrationSecretWatcher.Functions.net10.0.zip .

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.VersionPrefix }}${{ github.event.inputs.VersionSuffix && format('-{0}', github.event.inputs.VersionSuffix) || '' }}
          files: ./PosInformatique.Azure.Identity.AppRegistrationSecretWatcher.Functions.net10.0.zip
          overwrite_files: true
          draft: ${{ github.event.inputs.VersionSuffix == '' }}
          prerelease: ${{ github.event.inputs.VersionSuffix != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}